name: Build and Deploy to charliezchen.github.io/avalon

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js version 14
    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    # Install dependencies in the 'client' directory
    - name: Install Dependencies
      run: |
        cd client
        npm install

    # Build the application in the 'client' directory
    - name: Build
      run: |
        cd client
        npm run build
      env:
        VUE_APP_SERVER_URL: https://avalon-server-charlie.herokuapp.com
        
    - name: Deploy to charliezchen.github.io/avalon
      run: |
        git config --global user.name 'Charlie Chen'
        git config --global user.email 'charlie.chen@nyu.edu'
        git clone https://github.com/charliezchen/charliezchen.github.io.git
        cp -r client/dist/* charliezchen.github.io/avalon/
        cd charliezchen.github.io
        git remote set-url --push origin https://charliezchen:$GITHUB_TOKEN@github.com/charliezchen/charliezchen.github.io.git
        git add .
        git diff --staged --quiet || (
          short_sha=$(echo $GITHUB_SHA | cut -c1-7)
          git commit -m "Deploy Avalon update - $short_sha"
          git push
        )
      env:
        GITHUB_TOKEN: ${{ secrets.AUTH_TO_PERS_WEB }}
